### ISSUE TITLE
Run CI tests across multiple python versions (3.6-3.8)

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/ProGraML#118]
1. Add a python-version list to the CI matrix: 3.6, 3.7, and 3.8.
2. Update cache key to index on the python version: `key: ${{ matrix.os }}-${{ matrix.python-version }}-bazel`.
3. Use `actions/setup-python` to set up python:
```
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
```

Progress:
- [x] py3.6
- [x] py3.7
- [x] py3.8
